spring:
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/mybatis-plus?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    banner-mode: off  #springboot标志关闭
  application:
    name: sec-mc-platform
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
mybatis-plus:
  mapper-locations: classpath:com/itheima/mapper/xml/*Mapper.xml
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID";
      id-type: assign_id
      # 默认数据库表下划线命名
      table-underline: true
      table-prefix: tbl_
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false  #控制台输入标志关闭
  configuration:
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: com.itheima.enums
server:
  port: 8092
  #springboot默认日志级别是info，feign的debug日志就不会输出
  logging:
    level:
      com.tulingxueyuan.order.feign: debug
feign:
  client:
    config:
      product-service: #服务名
        loggerLevel: FULL
        connectTimeout: 5000 #连接超时时间
        readTimeout: 7000 #请求处理超时时间
        #requestInterceptors:
        #  - com.tulingxueyuan.order.feign.interceptor.CustomFeignInterceptor